### ISSUE TITLE
Add delete command

### ISSUE THREAD

**Issue by st3no** [elrhomariyounes/YoCli#2]
I guess a function that allows deletion is useful.
My idea is to add a guid (so as to have a unique identifier) and use it as a parameter to pass to the delete command.

@elrhomariyounes what do you think about it ?

**Comment by elrhomariyounes** [comment]
Hello @st3no, 
Good idea, the issue is printing Guids to the console will be too loaded. If you have an idea for the printing layout to make notes readable.

What do yo think about deleting by dates or content ?

1. Delete notes in a specified date (day, month) 
2. Delete notes written in a specified month
3. Delete notes where their content contains a value provided by the user
4. Combine Date and Content
